// define a variable to import the <Verifier> or <renamedVerifier> solidity contract generated by Zokrates
const Verifier = artifacts.require("Verifier");

const proof = require("../../zokrates/code/square/proof2.json");

// Test verification with correct proof
// - use the contents from proof.json generated from zokrates steps

contract("Verifier", (accounts) => {
  let contract;

  beforeEach(async () => {
    contract = await Verifier.new();
  });

  it("should be correct", async () => {
    const response = await contract.verifyTx(proof.proof, proof.inputs);
    assert.equal(response, true);
  });

  it("should be incorrect", async () => {
    const response = await contract.verifyTx(proof.proof, [3, 4]);
    assert.equal(response, false);
  });
});

// Test verification with incorrect proof
